%\VignetteIndexEntry{RNASeqGUI Installation}
%\VignetteDepends{}
%\VignetteKeywords{rnaseq,GTK2}
%\VignettePackage{RNASeqGUI}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% To compile this document
% library('cacheSweave'); rm(list=ls()); Sweave('install.Rnw', driver=cacheSweaveDriver())

\documentclass[12pt]{article}

<<style, eval=TRUE, echo=FALSE, results=tex>>=
BiocStyle::latex()
@

\usepackage{cite}
\usepackage{Sweave}
\usepackage{times}
\usepackage{hyperref}
\SweaveOpts{keep.source=TRUE,eps=FALSE,pdf=FALSE,png=TRUE,include=FALSE,width=4,height=4.5,resolution=150}
\setkeys{Gin}{width=0.5\textwidth}

% use a vertical rule for R output instead of prompts for R input
\usepackage{fancyvrb}
\definecolor{darkgray}{gray}{0.2}
\DefineVerbatimEnvironment{Sinput}{Verbatim}{xleftmargin=1em,formatcom={\color{darkgray}}}
\DefineVerbatimEnvironment{Soutput}{Verbatim}{xleftmargin=1em,frame=leftline,framerule=.6pt,rulecolor=\color{darkgray},framesep=1em,formatcom={\color{darkgray}}}
\fvset{listparameters={\setlength{\topsep}{0pt}}}
\renewenvironment{Schunk}{\vspace{\topsep}}{\vspace{\topsep}}
\textwidth=6.2in
\textheight=8.5in
\oddsidemargin=0.2in
\evensidemargin=0.2in
\headheight=0in
\headsep=0.7in

\title{RNASeqGUI Package Installation}
\author{Francesco Russo, Claudia Angelini}
\date{April 14 2014}

\begin{document}

\maketitle

\tableofcontents

\section{RGTK2 installation guide}

RNASeqGUI package needs GTK2 libraries to run.
Below, it is described how to install GTK2 libraries on Linux, Mac OS and Windows. \\

\subsection{For Linux users}

We tested RNASeqGUI on Ubuntu 12.04 (precise) 64-bit, Kernel Linux 3.2.0-37-generic, GNOME 3.4.2.\\

\noindent 1 - Open a terminal and type:\\

\texttt{sudo apt-get update}\\

\texttt{sudo apt-get install libgtk2.0-dev}\\

\noindent 2 - Type:\\

\texttt{sudo apt-get install libcurl4-gnutls-dev}\\

\noindent 3 - Type:\\

\texttt{sudo apt-get install libxml2-dev}


\subsection{For Mac OS users}


\noindent 1 - Install \texttt{Xcode} developer tools (at least version 5.0.1) from Apple Store (it is free).\\

\noindent 2 - Install \texttt{XQuartz-2.7.5.dmg} from  \texttt{http://xquartz.macosforge.org/landing/} \\

\noindent 3 - Install \texttt{GTK}$\_$\texttt{2.24.17}$\_$\texttt{X11.pkg} from \texttt{http://r.research.att.com} .


\subsection{For Windows users}

\noindent 1 - download \texttt{gtk+-bundle}$\_$\texttt{2.22.1-20101229}$\_$\texttt{win64.zip} from \newline
\texttt{http://ftp.gnome.org/pub/gnome/binaries/win64/gtk+/2.22/} . \\

\noindent 2 - This is a bundle containing the GTK+ stack and its dependencies for Windows. To use it, create some empty folder like \texttt{$C:\backslash opt \backslash gtk$} .\\

\noindent 3 - Unzip this bundle.\\

\noindent 4 - Now, you have to add the bin folder to your \texttt{PATH} variable. Make sure you have no other versions of \texttt{GTK+} in \texttt{PATH} variable. To do this, execute the following instructions:
Open \texttt{Control Panel}, click on \texttt{System and Security}, click on \texttt{System}, click on \texttt{Advanced System Settings}, click on \texttt{Environment Variables}. In the \texttt{Environment Variables} window you will notice two columns \texttt{User variables} for a user name and \texttt{System variables}. Change the \texttt{PATH} variable in the \texttt{System variables} to be \texttt{$C:\backslash opt \backslash gtk \backslash bin$} .\\

This is all you need to install the GTK2 libraries.\\

\section{Session Info}

<<sessInfo, results=tex, echo=FALSE>>=
toLatex(sessionInfo())
@

<<resetOptions, echo=FALSE>>=
options(prompt="> ", continue="+ ")
@ 

\end{document}
