barplotpathway <- function(fileName,Project,n){

 require(biomaRt)
 require(gage)
 require(pathview)
 require(latticeExtra)

 db <- InitDb(db.name='barplot_db', db.path=file.path("RNASeqGUI_Projects",Project,"Logs","cache"))
 SaveInCache(db, fileName, "filename_key")
 SaveInCache(db, Project,  "project_key")

 res=NULL 
 n = as.numeric(n)
 SaveInCache(db, n,  "n_key")
 print("Expression data selected: ") 
 print(fileName)
 res=read.table(fileName, row.names=1, header=TRUE)
 print("dimensions:")
 print(dim(res))
 print(head(res))

  if(Sys.info()[[1]]=="Windows"){

 a = subset(res, res[,4] < 0.05) # select significant 
   print("Performing barplot")
   print(dim(a))
   print(head(a))
   a=data.frame(a)

   print(barplot( -log10(a$q.val),names.arg=substring(rownames(a),10,24),las=2, col=rainbow(15), border="slateblue", main="Pathway Significance", ylab="-log10(q.val)", cex.names = 0.7,horiz = F))
   path=paste(getwd(),"\\RNASeqGUI_Projects\\",Project,"\\Plots\\",sep="")
   b=paste(path,"SignificancePathwayBarplot.pdf.pdf",sep="")
   dev.print(device = pdf, file=b)
   dev.off()

   a = a[n:(n+7),] # Select only some pathways
   mdat <- matrix( c(c(1:length(row.names(a))) , substring(rownames(a),10,24), -log10(a[,4]), substring(rownames(a),1,8)) , nrow = length(row.names(a)), ncol = 4, byrow = FALSE,dimnames = list(row.names(a),c("row", "path_name", "significance", "path_code")))
   write.table(file = paste(getwd(),"\\RNASeqGUI_Projects\\",Project,"\\Results\\mdat.txt",sep=""), mdat, quote=TRUE, row.names=FALSE)
   mdat<-read.table(paste(getwd(),"\\RNASeqGUI_Projects\\",Project,"\\Results\\mdat.txt",sep=""), header=TRUE, row.names=1)
   SaveInCache(db, mdat,  "mdat_key")
   print(cloud(significance~path_name+path_code, mdat, panel.3d.cloud=panel.3dbars, col.facet=rainbow(8), xbase=0.8, ybase=0.8, scales=list(arrows=FALSE, col=1), par.settings = list(axis.line = list(col = "transparent"))))
   path=paste(getwd(),"\\RNASeqGUI_Projects\\",Project,"\\Plots\\",sep="")
   b=paste(path,"Significance3DPathwayBarplot.pdf",sep="")
   dev.print(device = pdf, file=b)
   message=paste("The 'Significance3DPathwayBarplot.pdf' file has been saved in the ", Project,"\\Plots folder!", sep="")
   print(message)
    
    #write into the project report
    report=paste("RNASeqGUI_Projects\\",Project,"\\Logs\\report.Rmd",sep="")    
    message5 <- paste("  ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")    
    message2 <- paste(" * In the *Gene-Set\\Pathway Interface*, you clicked the **Pathway Barplot** button at `", Sys.time(),"` and the plots have been saved in the `", Project,"\\Plots` folder.", sep="")
    write(message2, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste("  ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n") 
    message5 <- paste(" ```{r} ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n") 

    message5 <- paste(" require(biomaRt)",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste(" require(gage)",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste(" require(pathview)",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n") 
    message5 <- paste(" require(lattice)",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")   

    message5 <- paste("db <- InitDb(db.name = 'barplot_db', db.path=file.path('cache'))", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n") 
    message5 <- paste( " n <- ", n,"", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n") 
    message5 <- paste( "fileName <- '", fileName,"'", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")   
    message5 <- paste( "print('Expression data selected: ')", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "print(fileName)", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "res=read.table(fileName, row.names=1, header=TRUE)", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "print(head(res))  ", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "a = subset(res, res[,4] < 0.05) # select significant ", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "a=data.frame(a)", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "print(barplot( -log10(a$q.val),names.arg=substring(rownames(a),10,24),las=2, col=rainbow(15), border='slateblue', main='Pathway Significance', ylab='-log10(q.val)', cex.names = 0.7,horiz = F))", sep="")   
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "a = a[n:(n+7),] # Select only some pathways", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n") 
    message5 <- paste( "mdat <- LoadCachedObject(db, 'mdat_key')", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "print(mdat)", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "#mdat <- matrix( c(c(1:length(row.names(a))) , substring(rownames(a),10,24), -log10(a[,4]), substring(rownames(a),1,8)) , nrow = length(row.names(a)), ncol = 4, byrow = FALSE,dimnames = list(row.names(a),c('row', 'path_name', 'significance', 'path_code')))", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")   
    message5 <- paste( "print(cloud(significance~path_name+path_code, mdat, panel.3d.cloud=panel.3dbars, col.facet=rainbow(8), xbase=0.8, ybase=0.8, scales=list(arrows=FALSE, col=1), par.settings = list(axis.line = list(col = 'transparent'))))", sep="")  
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")   
    message8 <- paste(" ``` ",sep="\n")
    write(message8, file = report,ncolumns = if(is.character(message8)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste(" _______________________________________________________________________ ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
  

  }else{         # Linux

   a = subset(res, res[,4] < 0.05) # select significant 
   print("Performing barplot")
   print(dim(a))
   print(head(a))
   a=data.frame(a)

    the.file2 = strsplit(fileName,"/")    
    the.file2 = the.file2[[1]][length(the.file2[[1]])]  #estract the namefile   
    name = substring(the.file2,1,nchar(the.file2)-4)  # eliminates ".txt"

   print(barplot( -log10(a$q.val),names.arg=substring(rownames(a),10,24),las=2, col=rainbow(15), border="slateblue", main="Pathway Significance", ylab="-log10(q.val)", cex.names = 0.7,horiz = F))
   path=paste(getwd(),"/RNASeqGUI_Projects/",Project,"/Plots/",sep="")
   b=paste(path,name,"_SignificancePathwayBarplot.pdf",sep="")
   dev.print(device = pdf, file=b)
   dev.off()

   a = a[n:(n+7),] # Select only some pathways
   mdat <- matrix( c(c(1:length(row.names(a))) , substring(rownames(a),10,24), -log10(a[,4]), substring(rownames(a),1,8)) , nrow = length(row.names(a)), ncol = 4, byrow = FALSE,dimnames = list(row.names(a),c("row", "path_name", "significance", "path_code")))
   write.table(file = paste(getwd(),"/RNASeqGUI_Projects/",Project,"/Results/mdat.txt",sep=""), mdat, quote=TRUE, row.names=FALSE)
   mdat<-read.table(paste(getwd(),"/RNASeqGUI_Projects/",Project,"/Results/mdat.txt",sep=""), header=TRUE, row.names=1)
   SaveInCache(db, mdat,  "mdat_key")
   print(cloud(significance~path_name+path_code, mdat, panel.3d.cloud=panel.3dbars, col.facet=rainbow(8), xbase=0.8, ybase=0.8, scales=list(arrows=FALSE, col=1), par.settings = list(axis.line = list(col = "transparent"))))
   path=paste(getwd(),"/RNASeqGUI_Projects/",Project,"/Plots/",sep="")
   b=paste(path,name,"_Significance3DPathwayBarplot.pdf",sep="")
   dev.print(device = pdf, file=b)
   message=paste("The plot has been saved in the ", Project,"/Plots folder!", sep="")
   print(message)
    
    #write into the project report
    report=paste("RNASeqGUI_Projects/",Project,"/Logs/report.Rmd",sep="")    
    message5 <- paste("  ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")    
    message2 <- paste(" * In the *Gene-Set/Pathway Interface*, you clicked the **Pathway Barplot** button at `", Sys.time(),"` and the plots have been saved in the `", Project,"/Plots` folder.", sep="")
    write(message2, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste("  ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n") 
    message5 <- paste(" ```{r} ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n") 

    message5 <- paste(" require(biomaRt)",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste(" require(gage)",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste(" require(pathview)",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n") 
    message5 <- paste(" require(lattice)",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")   

    message5 <- paste("db <- InitDb(db.name = 'barplot_db', db.path=file.path('cache'))", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
    message5 <- paste( "n <- ", n,"", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "fileName <- '", fileName,"'", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "print('Expression data selected: ')", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "print(fileName)", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "res=read.table(fileName, row.names=1, header=TRUE)", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "print(head(res))  ", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "a = subset(res, res[,4] < 0.05) # select significant ", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "a=data.frame(a)", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "print(barplot(-log10(a$q.val),names.arg=substring(rownames(a),10,24),las=2,col=rainbow(15),", sep="")   
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n") 
    message5 <- paste( "border='slateblue',main='Pathway Significance',ylab='-log10(q.val)',cex.names=0.7,horiz=F))", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "a = a[n:(n+7),] # Select only some pathways", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "mdat <- LoadCachedObject(db, 'mdat_key')", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n") 
    message5 <- paste( "print(mdat)", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "#mdat<-matrix(c(c(1:length(row.names(a))),substring(rownames(a),10,24),-log10(a[,4]),", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n") 
    message5 <- paste( "#substring(rownames(a),1,8)),nrow=length(row.names(a)),ncol=4,byrow=F,dimnames=list(row.names(a),", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n") 
    message5 <- paste( "#c('row','path_name','significance','path_code')))", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "print(cloud(significance~path_name+path_code,mdat,panel.3d.cloud=panel.3dbars,col.facet=rainbow(8),", sep="")  
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste( "xbase=0.8,ybase=0.8,scales=list(arrows=F,col=1),par.settings=list(axis.line=list(col='transparent'))))", sep="") 
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message8 <- paste(" ``` ",sep="\n")
    write(message8, file = report,ncolumns = if(is.character(message8)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste(" _______________________________________________________________________ ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
  
  }
  
  print('FINISHED!')  
  res

}


