EdgeRComplexDesign <- function(x, n, factors, the.file, fdr, LibraryLayout, Project, coe){

  require(edgeR)
  require(limma)
  coe = as.numeric(coe)

  fdr = as.numeric(fdr)

  g <- factor(factors)

  if(Sys.info()[[1]]=="Windows"){
    a=paste(getwd(),"\\RNASeqGUI_Projects\\",Project,"\\Plots\\",sep="")
    the.file2 = strsplit(the.file,"\\\\")
    the.file2 = the.file2[[1]][length(the.file2[[1]])]  #estract the namefile
    sys.sep='\\'
  }else{
    a=paste(getwd(),"/RNASeqGUI_Projects/",Project,"/Plots/",sep="")
    the.file2 = strsplit(the.file,"/")
    the.file2 = the.file2[[1]][length(the.file2[[1]])]  #estract the namefile
    sys.sep='/'
  }


  db <- InitDb(db.name=paste(the.file2,'edgercomplex.db',sep="_"), db.path=file.path("RNASeqGUI_Projects",Project,"Logs","cache"))
  
  SaveInCache(db, the.file, "the_file_key")
  SaveInCache(db, Project, "project_key")
  SaveInCache(db, x, "maindataframe_key")
  SaveInCache(db, n, "n_key")
  SaveInCache(db, factors, "factors_key")
  SaveInCache(db, LibraryLayout, "g_key")
  SaveInCache(db, fdr, "fdr_key")
  SaveInCache(db, coe, "coe_key")

  res9 <- DGEList(counts = x[,1:n], group=g)  # modify here the entries of the count columns
  SaveInCache(db, res9, "res9_key")
  
  print("You loaded this count file: ")
  print(head(res9$counts))

  colnames(res9) <- factor(c(1:n))

  res9 <- calcNormFactors(res9)
  SaveInCache(db, res9, "res9normfact_key")

  print("Summary of the design: ")

  print(res9$samples)

  design=model.matrix( ~ LibraryLayout + g )
  # design=model.matrix( ~ g)
  SaveInCache(db, design, "design_key")

  print("Experimental design:")
  print(design)

  d2 = estimateGLMTrendedDisp(res9, design)
  SaveInCache(db, d2, "d2trenddisp_key")
 
  d2 = estimateGLMTagwiseDisp(d2, design)
  SaveInCache(db, d2, "d2tagdisp_key")

  f = glmFit(d2, design)
  SaveInCache(db, f, "f_key")
  #makeConstrast(B-A,levels=design)

  de = glmLRT(f, coef=coe)
  SaveInCache(db, de, "de_key")
  
  tt = topTags(de, n=nrow(res9))
  SaveInCache(db, tt, "tt_key")
  
  print("First five lines of the result table: ")
  print(head(tt$table))

  rn = rownames(tt$table)

  if(Sys.info()[[1]]=="Windows"){
 
   a=paste(getwd(),"\\RNASeqGUI_Projects\\",Project,"\\Results",sep="")
    #outputName=paste(the.file2,"_results_EdgeRComplexDesign.txt", sep="")
   # b=paste(a,outputName,sep="\\")
   # sys.sep='\\'
  }else{

    a=paste(getwd(),"/RNASeqGUI_Projects/",Project,"/Results",sep="")
   # #outputName=paste(the.file2,"_results_EdgeRComplexDesign.txt", sep="")
   # b=paste(a,outputName,sep="/")
   # sys.sep='/'
  }
  
  et9_results <- topTags( tt, n = nrow( tt$table ) , sort.by = "none" )$table # n = nrow( et9$table ) is used to print all results!
  SaveInCache(db, et9_results, "et9results_key")
  
  outputName=paste(the.file2,"_results_EdgeRComplexDesign.txt", sep="")
  b=paste(a,outputName,sep=sys.sep)
  et9_results$id <- rownames(et9_results)
  et9_results<-(et9_results[,c(6,1,2,3,4,5)])
  write.table( et9_results, file = b , quote=FALSE, sep="\t", row.names=FALSE)
  #write.table(et9_results, file = b , quote=FALSE, sep="\t", row.names=TRUE)

  outputName=paste(the.file2,"_results_EdgeRComplexDesign.tsv", sep="")
  b=paste(a,outputName,sep=sys.sep)
  write.table( et9_results, file = b , quote=FALSE, sep="\t", row.names=FALSE)

  list_DE_EDGER = subset(et9_results, FDR<fdr) # select significant genes
  SaveInCache(db, list_DE_EDGER, "listdeedger_key")
  
  outputName=paste(the.file2,"_fdr=",fdr,"_DE_genes_EdgeRComplexDesign.txt", sep="")
  b=paste(a,outputName,sep=sys.sep)
  write.table(list_DE_EDGER, file = b , quote=FALSE, sep="\t", row.names=FALSE)

  outputName=paste(the.file2,"_fdr=",fdr,"_DE_genes_EdgeRComplexDesign.tsv", sep="")
  b=paste(a,outputName,sep=sys.sep)
  write.table(list_DE_EDGER, file = b , quote=FALSE, sep="\t", row.names=FALSE)

  message=paste("Results of EdgeRComplexDesign have been saved in the Results folder of ",Project," project!", sep="")
  print(message)

  outputName=paste(the.file2,"_MDS_EdgeRComplexDesign.pdf", sep="")

  a=paste(getwd(),"RNASeqGUI_Projects",Project,"Plots",sep=sys.sep)

  b=paste(a,outputName,sep=sys.sep)

  plotMDS(res9, labels=res9$samples$group,col=c("red","blue")[factor(g)])

  dev.print(device = pdf, file=b)
  
  if(Sys.info()[[1]]=="Windows"){
    #write into the project report
    report=paste("RNASeqGUI_Projects\\",Project,"\\Logs\\report.Rmd",sep="")
    
    message5 <- paste("  ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
    
    message2 <- paste(" * In the *EdgeR Interface*, you clicked the **Run EdgeRComplexDesign** button at `", Sys.time(),"` and the ",outputName," file has been saved in the `", Project,"\\Plots` folder.", sep="")
    write(message2, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "\n")
    message5 <- paste("  ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")    
    message2 <- paste("You chose the following count file: `",the.file,"`, fdr: `",fdr,"`, Project: `",Project,"`, ",sep="\n")
    write(message2, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "\n")    
    message1 <- paste("factors= c(")
    write(message1, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "")    
    message2 <- paste("'",factors[1:(length(factors)-1)],"',",sep="")
    write(message2, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "")    
    message3 <- paste("'",factors[length(factors)],"'",sep="")
    write(message3, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "")   
    message4 <- paste("), ")
    write(message4, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "")    
    message1 <- paste("LibTypes= c(")
    write(message1, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "")    
    message2 <- paste("'",LibraryLayout[1:(length(LibraryLayout)-1)],"',",sep="")
    write(message2, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "")    
    message3 <- paste("'",LibraryLayout[length(LibraryLayout)],"'",sep="")
    write(message3, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "")    
    message4 <- paste("). ")
    write(message4, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "")    
    message5 <- paste("  ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")   
    message5 <- paste(" This R code has been run:",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste("  ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste(" ```{r} ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste("require(edgeR)",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste("require(limma)",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n") 
    message5 <- paste("the.file2='",the.file2,"'",sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")   
message5 <- paste("db <- InitDb(db.name=paste(the.file2,'edgercomplex.db',sep='_'), db.path=file.path('cache'))", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("x <- LoadCachedObject(db, 'maindataframe_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("the.file <- LoadCachedObject(db, 'the_file_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("Project <- LoadCachedObject(db, 'project_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("n <- LoadCachedObject(db, 'n_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("factors <- LoadCachedObject(db, 'factors_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("g <- LoadCachedObject(db, 'g_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("fdr <- LoadCachedObject(db, 'fdr_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("coe <- LoadCachedObject(db, 'coe_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("#res9 <- DGEList(counts = x[,1:n], group=g)  # modify here the entries of the count columns", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("res9 <- LoadCachedObject(db, 'res9_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("print('You loaded this count file: ') ", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("print(head(res9$counts)) ", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("colnames(res9) <- factor(c(1:n))", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("#res9 <- calcNormFactors(res9)", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("res9 <- LoadCachedObject(db, 'res9normfact_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("#design=model.matrix( ~ LibraryLayout + g)", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("design <- LoadCachedObject(db, 'design_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("#d2 = estimateGLMTrendedDisp(res9, design)", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("d2 <- LoadCachedObject(db, 'd2trenddisp_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("#d2 = estimateGLMTagwiseDisp(d2, design)", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("d2 <- LoadCachedObject(db, 'd2tagdisp_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("#f = glmFit(d2, design)", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("f <- LoadCachedObject(db, 'f_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("#de = glmLRT(f, coef=coe)", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("de <- LoadCachedObject(db, 'de_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("#tt = topTags(de, n=nrow(res9))", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("tt <- LoadCachedObject(db, 'tt_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("print('First five lines of the result table: ')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("print(head(tt$table))", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("rn = rownames(tt$table)", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
    message5 <- paste("#et9_results <- topTags( tt, n = nrow( tt$table ) , sort.by = 'none' )$table # n = nrow( et9$table ) is used to print all results!", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
    message5 <- paste("et9_results <- LoadCachedObject(db, 'et9results_key')", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
    message5 <- paste("plotMDS(res9, labels=res9$samples$group,col=c('red','blue')[factor(g)]) ", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")        
    message8 <- paste(" ``` ",sep="\n")
    write(message8, file = report,ncolumns = if(is.character(message8)) 1 else 5,append = TRUE, sep = "\n")   
    message5 <- paste(" _______________________________________________________________________ ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
    
    print("FINISHED !")
    
    et9_results

  }else{ #Linux

    #write into the project report
    report=paste("RNASeqGUI_Projects/",Project,"/Logs/report.Rmd",sep="")    
    message5 <- paste("  ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")   
    message2 <- paste(" * In the *EdgeR Interface*, you clicked the **Run EdgeRComplexDesign** button at `", Sys.time(),"` and the ",outputName," file has been saved in the `", Project,"/Plots` folder.", sep="")
    write(message2, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste("  ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")    
    message2 <- paste("You chose the following count file: `",the.file,"`, fdr: `",fdr,"`, Project: `",Project,"`, ",sep="\n")
    write(message2, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "\n")    
    message1 <- paste("factors= c(")
    write(message1, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "")    
    message2 <- paste("'",factors[1:(length(factors)-1)],"',",sep="")
    write(message2, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "")    
    message3 <- paste("'",factors[length(factors)],"'",sep="")
    write(message3, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "")   
    message4 <- paste("), ")
    write(message4, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "")    
    message1 <- paste("LibTypes= c(")
    write(message1, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "")    
    message2 <- paste("'",LibraryLayout[1:(length(LibraryLayout)-1)],"',",sep="")
    write(message2, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "")    
    message3 <- paste("'",LibraryLayout[length(LibraryLayout)],"'",sep="")
    write(message3, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "")    
    message4 <- paste("). ")
    write(message4, file = report,ncolumns = if(is.character(message2)) 1 else 5,append = TRUE, sep = "")    
    message5 <- paste("  ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")   
    message5 <- paste(" This R code has been run:",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste("  ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste(" ```{r} ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste("require(edgeR)",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")    
    message5 <- paste("require(limma)",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
    message5 <- paste("the.file2='",the.file2,"'",sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")  
message5 <- paste("db <- InitDb(db.name=paste(the.file2,'edgercomplex.db',sep='_'), db.path=file.path('cache'))", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("x <- LoadCachedObject(db, 'maindataframe_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("the.file <- LoadCachedObject(db, 'the_file_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("Project <- LoadCachedObject(db, 'project_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("n <- LoadCachedObject(db, 'n_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("factors <- LoadCachedObject(db, 'factors_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("g <- LoadCachedObject(db, 'g_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("fdr <- LoadCachedObject(db, 'fdr_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("coe <- LoadCachedObject(db, 'coe_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("#res9 <- DGEList(counts = x[,1:n], group=g)  # modify here the entries of the count columns", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("res9 <- LoadCachedObject(db, 'res9_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("print('You loaded this count file: ') ", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("print(head(res9$counts)) ", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("colnames(res9) <- factor(c(1:n))", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("#res9 <- calcNormFactors(res9)", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("res9 <- LoadCachedObject(db, 'res9normfact_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("#design=model.matrix( ~ LibraryLayout + g)", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("design <- LoadCachedObject(db, 'design_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("#d2 = estimateGLMTrendedDisp(res9, design)", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("d2 <- LoadCachedObject(db, 'd2trenddisp_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("#d2 = estimateGLMTagwiseDisp(d2, design)", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("d2 <- LoadCachedObject(db, 'd2tagdisp_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("#f = glmFit(d2, design)", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("f <- LoadCachedObject(db, 'f_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("#de = glmLRT(f, coef=coe)", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("de <- LoadCachedObject(db, 'de_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("#tt = topTags(de, n=nrow(res9))", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("tt <- LoadCachedObject(db, 'tt_key')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("print('First five lines of the result table: ')", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("print(head(tt$table))", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
message5 <- paste("rn = rownames(tt$table)", sep="")
write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
    message5 <- paste("#et9_results <- topTags( tt, n = nrow( tt$table ) , sort.by = 'none' )$table # n = nrow( et9$table ) is used to print all results!", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
    message5 <- paste("et9_results <- LoadCachedObject(db, 'et9results_key')", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
    message5 <- paste("plotMDS(res9, labels=res9$samples$group,col=c('red','blue')[factor(g)]) ", sep="")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")        
    message8 <- paste(" ``` ",sep="\n")
    write(message8, file = report,ncolumns = if(is.character(message8)) 1 else 5,append = TRUE, sep = "\n")   
    message5 <- paste(" _______________________________________________________________________ ",sep="\n")
    write(message5, file = report,ncolumns = if(is.character(message5)) 1 else 5,append = TRUE, sep = "\n")
    
    print("FINISHED !")
    
    et9_results

  }

}
